### ISSUE TITLE
Update project to Java 8

### ISSUE THREAD

**Issue by britter** [scrum-for-developers/worblehat#13]
Make use of `java.util.Optional` (for example in `BookRepository.findBookByIsbn(String)`), Streaming API and Time API.

**Comment by AndreasEK** [comment]
Ok, so we addressed some of the proposals. At least in some places. Where exactly would you like to see the Time API?

**Comment by britter** [comment]
I definitely want to get rid of joda-time in Borrowing and use `java.time.LocalDate` for persistence instead of `java.util.Date`

**Comment by britter** [comment]
I'll open a new issue für the Time API thing
