### ISSUE TITLE
Tabs and Spaces

### ISSUE THREAD

**Issue by britter** [scrum-for-developers/worblehat#15]
Traditionally the worblehat project used tabs for indentation (since we used it with Eclipse and the Eclipse default formatter uses spaces). Now that more and more of us are using IntelliJ, we have a mix of tab and space indented files in the code base.

We should decide on one style for indentation and document this for example using [editorconfig](http://editorconfig.org).

**Comment by britter** [comment]
It may be necessary to add the corresponding [plugin to Eclipse](https://github.com/ncjones/editorconfig-eclipse) for editorconfig to work.

**Comment by AndreasEK** [comment]
One of the first things I always told students is to setup the IDE in a similar way, which included tabs/spaces, encoding and linebreaks. Initially that was somewhere in the root module, but nowadays editorconfig seems to be the way to go.

As far as I can tell, most of the files uses tabs. Is there a reason to change that? (opening the tab vs. spaces discussion)

**Comment by britter** [comment]
IntelliJ uses spaces as default. Since we're currently going in the IntelliJ direction, this would be an argument for using spaces (beside "it's just the right thing to do" ;-) )

**Comment by AndreasEK** [comment]
There's indeed an editorconfig nowadays:
https://github.com/scrum-for-developers/worblehat/blob/08b44a9af606d1b3a924b311a98ce0a8bee9cfbe/.editorconfig#L4
