### ISSUE TITLE
Use BDDMockito

### ISSUE THREAD

**Issue by britter** [scrum-for-developers/worblehat#17]
The `BDDMockito` class defines some methods that allow to build mock expectations in BDD style:

`given(myMock.doSomething()).willReturn(someValue)`

**Comment by AndreasEK** [comment]
Do you still - nearly two years after opening the issue - vote for including the library?

**Comment by britter** [comment]
It's not a different library. It's only a different API inside mockito. I still think it is better than the classical API.

**Comment by AndreasEK** [comment]
nothing happened in the last 7 years … it's still an option, but apparently, there was not enough caring in the years. closing the issue <3
