### ISSUE TITLE
Consider using Maven Wrapper

### ISSUE THREAD

**Issue by Riggs333** [scrum-for-developers/worblehat#33]
https://github.com/takari/maven-wrapper

**Comment by britter** [comment]
Definitely a good idea. How do you deal with child modules? Do you add a maven wrapper for each module or just one on the top level of the project?

**Comment by Riggs333** [comment]
Honestly I have no idea how it works with child modules.
But I guess @AndreasEK found out while testing his PR scrum-for-developers/worblehat-youtube#38 :-)

**Comment by Riggs333** [comment]
(whoops, didn't meant to close the issue.)
