### ISSUE TITLE
Consider migration from Hamcrest to AssertJ

### ISSUE THREAD

**Issue by Riggs333** [scrum-for-developers/worblehat#34]
I know this topic is for many people a matter of taste. :-)
But I see lots of arguments for favoring AssertJ over Hamcrest (like readability, IDE support / code completion, feature set, ...).
If you decide to use it I'd be happy to help with the migration.

**Comment by britter** [comment]
My idea for the testing part is to upgrade to JUnit 5 and then use AssertJ, since JUnit 5 does not have a hamcrest bundled. So you really need to decide which style of assertion you like the most.

**Comment by AndreasEK** [comment]
If either of you happens to still care enough, a PR is welcome. Otherwise, I'll close this issue for now.

**Comment by Riggs333** [comment]
Sure - I just created PR #55.
