### ISSUE TITLE
Unused Method with wrong DB queries in BookRepository

### ISSUE THREAD

**Issue by MaPePeR** [scrum-for-developers/worblehat#5]
https://github.com/scrum-for-developers/worblehat/blob/f4f988a27e6e4f5286a1a2143430f4f914be1801/worblehat-domain/src/main/java/de/codecentric/psd/worblehat/domain/BookRepository.java#L42-L60

Give a totally wrong idea on how to query the database.

**Comment by britter** [comment]
Yes this definitely should go away. Do you want to submit a PR for this?

**Comment by britter** [comment]
Fixed in 0e499413b8fece5ef1eb2cea136072e0f2f2bf67
